<a href="https://colab.research.google.com/github/tomek-l/fire/blob/master/tests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/tomek-l/fire/master/model.py

--2020-01-20 22:07:38--  https://raw.githubusercontent.com/tomek-l/fire/master/model.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2490 (2.4K) [text/plain]
Saving to: ‘model.py’

model.py            100%[===================>]   2.43K  --.-KB/s    in 0s      

2020-01-20 22:07:38 (85.4 MB/s) - ‘model.py’ saved [2490/2490]



In [2]:
BACKBONES = ['resnet18','resnet34','resnet50','resnet101', 'densenet121']
from model import Model
import torch
for b in BACKBONES:
    print(b)
    model = Model(backbone=b)
    model = model.cuda()
    print(model(torch.ones(1,3,224,224).cuda()))

resnet18


Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|██████████| 44.7M/44.7M [00:04<00:00, 9.48MB/s]


tensor([[0.5362]], device='cuda:0', grad_fn=<SigmoidBackward>)
resnet34


Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/checkpoints/resnet34-333f7ec4.pth
100%|██████████| 83.3M/83.3M [00:04<00:00, 17.7MB/s]


tensor([[0.3919]], device='cuda:0', grad_fn=<SigmoidBackward>)
resnet50


Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/checkpoints/resnet50-19c8e357.pth
100%|██████████| 97.8M/97.8M [00:10<00:00, 10.1MB/s]


tensor([[0.4509]], device='cuda:0', grad_fn=<SigmoidBackward>)
resnet101


Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /root/.cache/torch/checkpoints/resnet101-5d3b4d8f.pth
100%|██████████| 170M/170M [00:14<00:00, 12.7MB/s]


tensor([[0.4090]], device='cuda:0', grad_fn=<SigmoidBackward>)
densenet121


Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to /root/.cache/torch/checkpoints/densenet121-a639ec97.pth
100%|██████████| 30.8M/30.8M [00:01<00:00, 19.5MB/s]


tensor([[0.3427]], device='cuda:0', grad_fn=<SigmoidBackward>)
